### ISSUE TITLE
Functionality of StalinSort

### ISSUE THREAD

**Issue by ruidazeng** [gurbaflurb/StalinSort#1]
Could you please kindly explain the methodology of StalinSort?

**Comment by gurbaflurb** [comment]
Stalin Sort is a O(n) sorting algorithm by which elements are either in the requested order or eliminated. This follows the historical methodology that was used by Joseph Stalin's secret police to systematically eliminate any opposition, which in this case, is any value that is not in line with the direction of the sort (either ascending or descending).

A quick example would be:
Stalin sort the values from lowest to highest
Before: 1 3 2 4 5 10 9
After: 1 3 4 5 10
Having eliminated the opposition (2 and 9), the values are now in order.

Another example would be:
Sort the array of faithful Russian politicians
Before: {"Lavrentiy Beria", "Yevgeny Miller", "Nikolai Yezhov", "Joseph Stalin", "Sergey Kirov"}
After: {"Lavrentiy Beria", "Nikolai Yezhov", "Joseph Stalin"}
Having eliminated the opposition (Yevgeny Miller and Sergey Kirov), all politicians are now loyal to Stalin.
